# Generated by Django 5.0.6 on 2024-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDBcomponent', '0002_rename_insousers_infousers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infousers',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Доп. инф. пользователей'},
        ),
        migrations.AlterField(
            model_name='infousers',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='infousers',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='infousers',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='infousers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
